### ISSUE TITLE
Issue on page /book/about/syllabus.html

### ISSUE THREAD

**Issue by camicasilo** [giswqs/geog-312#53]
hello,

when a try to access to syllabus it shows this message

![imagen](https://github.com/user-attachments/assets/5d0612ba-e708-47c8-a573-aec971b2598a)

and the same with Schedule 

![imagen](https://github.com/user-attachments/assets/b8efc954-954e-45b2-ba31-2b6db21b2592)

thanks

**Comment by giswqs** [comment]
Is Google blocked? Can you open Google Docs?

**Comment by camicasilo** [comment]
yes, I can

![imagen](https://github.com/user-attachments/assets/1a37335d-a1cb-4793-be7c-57fa310f0623)

**Comment by camicasilo** [comment]
Is working right now, thanks.
