### ISSUE TITLE
Geemap and laeafmap installing using Mamba and Jupyter Lab issue

### ISSUE THREAD

**Issue by Raj6112** [giswqs/geog-312#71]
Hi, I am facing two issues while referring Intro to GIS Programming Week 1: Introduction to Conda, Mamba, VS Code, and Git You tube lecture. 

1. When i try to intsall Geemap and laeafmap using  "(geo) C:\Users\A132054>mamba install -c conda-forge geemap leafmap"  i am getting following error - 

- Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/win-64/icu-68.2-h0e60522_0.tar.bz2]
Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds

![image](https://github.com/user-attachments/assets/f98f4b12-42be-4bb4-99d5-669c7aa0434b)

below two snips are for same error due to multiple lines of error i kept them those two in order..

![image](https://github.com/user-attachments/assets/23f045b3-d8da-40b6-8615-9ce704f6d4f3)

![image](https://github.com/user-attachments/assets/77a03843-904c-4512-9a08-fd9580506631)

- An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

**2 -** Despite above error when i try to open Jupyter lab using following command

**(base) C:\Users\A132054> cd .\Documents\GIS_Prog

(base) C:\Users\A132054\Documents\GIS_Prog> conda activate geo

(geo) C:\Users\A132054\Documents\GIS_Prog> jupyter lab**

This redirecting me to Virtual Studio in Browser (Below Image )

![image](https://github.com/user-attachments/assets/6095b5a3-9602-40ea-b939-d91920303e4a)

and Command Prompt giving error like below - 

[main 2024-09-22T07:21:59.509Z] update#setState idle
[5048:0922/125209.860:ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -101
[main 2024-09-22T07:22:29.520Z] update#setState checking for updates
[main 2024-09-22T07:22:29.527Z] update#setState downloading
[main 2024-09-22T07:22:29.531Z] update#setState downloaded

Please help in this
@giswqs

**Comment by giswqs** [comment]
It is your network problem. If conda doesn't work, try pip install

**Comment by Raj6112** [comment]
Thank you Sir for Providing soloution. It would be really helpful if you can also suggest on second issue. Regarding Jupyter lab
