### ISSUE TITLE
Issue with VScode hover-over 

### ISSUE THREAD

**Issue by felwind14** [giswqs/geog-312#80]
Dear Professor:

I was running this pieces of code rasterio.plot.show(src, cmap = "terrain", ax=ax, title="Digital Elevation Model (DEM)") and I noticed in the video that once you hover-over cmap different map color options appear. In my case this does not happen and for example I do this:

rasterio.plot.show(src, cmap = "<**ctrl+space**>", ax=ax, title="Digital Elevation Model (DEM)")  -->then the documentation of subplots appears but no information about cmap. 

Also I read that python language server needed to be chanced from the default to pylance but still it does not work.

Questions:

- How can I fix this?
- Should we expect from Vscode comprehensive hints about these kind of arguments or maybe better always to refer to the documentation?
Thank you

**Comment by giswqs** [comment]
You may need to install pylance or GitHub Copilot extensions.
