### ISSUE TITLE
Maplibregl not found in leafmap

### ISSUE THREAD

**Issue by DeutschZaw** [giswqs/geog-312#82]
At the lecture of "Intro to GIS Programming | Week 1: Introduction to Conda, Mamba, VS Code, and Git", 
I have already installed the leafmap but when I run the "overture.ipynb" (downloaded from leafmap website) in Jupyterlab, there was an error: it says:

"---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 import leafmap.maplibregl as leafmap

File [~\anaconda3\envs\geo\Lib\site-packages\leafmap\maplibregl.py:10](http://localhost:8888/lab/tree/~/anaconda3/envs/geo/Lib/site-packages/leafmap/maplibregl.py#line=9)
      8 import ipyvuetify as v
      9 from box import Box
---> 10 from maplibre.basemaps import background
     11 from maplibre.basemaps import construct_carto_basemap_url
     12 from maplibre.ipywidget import MapWidget

ModuleNotFoundError: No module named 'maplibre'
"
I have attached the screenshot of this error.
![error](https://github.com/user-attachments/assets/68628b74-054b-462c-9fe8-e44e5265e48a)

What should I do? Should I try installing maplibre using pip method?

**Comment by giswqs** [comment]
maplibre is now an option dependency for leafmap. You will have to install explicitly using either pip or mamba. 
`pip install maplibre` or `mamba install -c conda-forge maplibre`

**Comment by DeutschZaw** [comment]
It works! Thank you, sir

**Comment by Iamnyatichi** [comment]
I was stuck there too. Thank you Dr. I am okay now
