### ISSUE TITLE
Issue on page /book/software/miniconda.html

### ISSUE THREAD

**Issue by Sulaiman45599** [giswqs/geog-312#92]
![Screenshot 2024-10-03 191349](https://github.com/user-attachments/assets/93b3eb0a-3152-45dc-9e08-0dd66bf3c5f5)
i face this isse

**Comment by giswqs** [comment]
Try uv if mamba does not work for you. 
https://youtu.be/-YnfmHBHkWQ?si=dipB2m4wGoIjSin3

**Comment by Sulaiman45599** [comment]
i try to deactivate conda in terminal not they don't deactivate
