### ISSUE TITLE
Issue on page /book/software/overview.html

### ISSUE THREAD

**Issue by Sulaiman45599** [giswqs/geog-312#93]
Your issue content here.
![Screenshot 2024-10-03 212007](https://github.com/user-attachments/assets/3b86b584-21d8-4f5f-9e5a-83aa040f054a)

conda is not deactivate

**Comment by giswqs** [comment]
This is a mamba issue irrelevant to this course. Please Google it or report an issue to the mamba repo. https://github.com/mamba-org/mamba
