### ISSUE TITLE
i face issue in download a uv package

### ISSUE THREAD

**Issue by Sulaiman45599** [giswqs/geog-312#94]
![Screenshot 2024-10-03 212605](https://github.com/user-attachments/assets/83b3b1a6-3e85-4a19-8539-9f8b42385763)

**Comment by giswqs** [comment]
Please make sure you follow the video tutorial closely to install uv. https://youtu.be/-YnfmHBHkWQ
Don't open an issue for every problem you into. This is not really a issue for this course. 
Post questions at the Discussion board. https://github.com/giswqs/geog-312/discussions
